# Generated by Django 5.0.7 on 2024-08-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('ProductName', models.CharField(max_length=20)),
                ('productPrice', models.CharField(max_length=20)),
                ('DiscountPrice', models.CharField(max_length=20)),
            ],
        ),
    ]
